### PR TITLE
exposes initialized k8s clients for guest and host frameworks

### PR DESCRIPTION
**Pull request by xh3b4sd**
Towards https://github.com/giantswarm/giantswarm/issues/2737. The idea is here to let us use the k8s clients freely during development. Once we notice functionality becomes common ground we can move it to the framework but for prototyping and playing around it is super useful to have the clients setup and available in integration tests.

### CODE REVIEW

**Review by fgimenez — APPROVED** [review]
LGTM

**Comment by xh3b4sd** [comment]
Note that I also exposed the rest config being created by the frameworks. We can probably drop this at some point in the future but for now I want to be free to experiment a little bit in integration tests to see how it can work when dealing with host and gest clusters within the same integration test.

**Review by kopiczko — APPROVED** [review]

**Comment by fgimenez** [comment]
:+1: with the config exposed this can be simplified https://github.com/giantswarm/helmclient/blob/master/integration/test/basic/basic_test.go#L23-L30

**Comment by xh3b4sd** [comment]
Yeah totally. I am thinking to maybe even create the appr and helm clients with the frameworks setup internally. Then we can drop this at all but lets see where this goes. Lets get experiences first and iterate from here.

**Pull request merged**
