### PR TITLE
Use multiwrite to also write to stdout

### PR DESCRIPTION
**Pull request by MarcelMue**
towards https://github.com/giantswarm/giantswarm/issues/4233

### CODE REVIEW

**Comment by MarcelMue** [comment]
@kopiczko please take a look if this would be helpful for debugging our issues in aws-operator.

**Comment by MarcelMue** [comment]
Vendored into `aws-operator` here: https://circleci.com/gh/giantswarm/aws-operator/11670

**Comment by MarcelMue** [comment]
Circle isn't playing nice here, uncertain if this has any benefit at all:
```
Your output is too large to display in the browser. Only the first 400000 characters are displayed.
You can download the output once this step is finished.
```

**Comment by kopiczko** [comment]
> Circle isn't playing nice here, uncertain if this has any benefit at all

Yeah, totally forgot about that crap. I think it doesn't make much sense in that case.

**Comment by MarcelMue** [comment]
Agreed, closing.

**Pull request closed without merging**
