### PR TITLE
uses giantswarm/backoff lib

### PR DESCRIPTION
**Pull request by xh3b4sd**
Towards https://github.com/giantswarm/giantswarm/issues/3902.

### CODE REVIEW

**Review by indyfree — APPROVED** [review]
When CI runs through this looks cool! Also thanks for taking the time and scoping and naming some thing corectly.

**Review by fgimenez — APPROVED** [review]
LGTM, CI build failed, would be good to have a full run.

**Comment by xh3b4sd** [comment]
I see. 

```
Get https://registry-1.docker.io/v2/library/alpine/manifests/3.7: EOF
2018/08/07 13:42:10 could not execute workflow: exit status 1
Exited with code 1
```

Does that ring a bell?

**Comment by xh3b4sd** [comment]
See https://github.com/giantswarm/giantswarm/issues/3930.

**Pull request merged**
