### PR TITLE
purges releases before installing them

### PR DESCRIPTION
**Pull request by xh3b4sd**
We saw lots of issues recently where retries caused helm commands to fail. This PR tries to help with these problems.

### CODE REVIEW

**Review by fgimenez — APPROVED** [review]
Nice thx, there's an error in CI on image build, probably ignorable (it just failed in one of the jobs, the image was properly built in the rest of them).

**Comment by xh3b4sd** [comment]
Why does it fail though? Can we improve on this? I do not see what went wrong. Can we improve logging and retry or something?

**Review by indyfree — APPROVED** [review]
LGTM if CI is not a problem.

**Comment by xh3b4sd** [comment]
Rerun, green now.

**Comment by fgimenez** [comment]
> Why does it fail though? Can we improve on this? I do not see what went wrong. Can we improve logging and retry or something?

Sure, I've proposed #60 to show the eventual build errors.

**Pull request merged**
