### PR TITLE
Update alpine to 3.8

### PR DESCRIPTION
**Pull request by marians**
For https://github.com/giantswarm/giantswarm/issues/4197

### CODE REVIEW

**Comment by marians** [comment]
Hmm. We have some unsatisfiable constraints:

```
ERROR: unsatisfiable constraints:
  build-base-0.5-r1:
    breaks: world[build-base=0.5-r0]
  git-2.18.0-r0:
    breaks: world[git=2.15.2-r0]
  iptables-1.6.2-r0:
    breaks: world[iptables=1.6.1-r1]
  jq-1.6_rc1-r1:
    breaks: world[jq=1.5-r5]
  less-530-r0:
    breaks: world[less=520-r0]
  openssh-client-7.7_p1-r3:
    breaks: world[openssh-client=7.5_p1-r8]
  openssl-1.0.2o-r2:
    breaks: world[openssl=1.0.2o-r1]
  sudo-1.8.23-r2:
    breaks: world[sudo=1.8.21_p2-r1]
```

**Comment by marians** [comment]
BTW, if somebody wants to take this over, please do.

**Comment by fgimenez** [comment]
> Hmm. We have some unsatisfiable constraints:

You just need to upgrade to the given new versions, eg. `build-base=0.5-r0 -> build-base=0.5-r1`

**Comment by fgimenez** [comment]
@marians should be fixed with https://github.com/giantswarm/e2e-harness/pull/124/commits/142b3bb5d0c0abe78e5757f274f3490677c5881a

**Comment by marians** [comment]
Cool, thanks!

**Pull request merged**
