### PR TITLE
refactor InstallOperator to make use of InstallResource

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Follow-up from https://github.com/giantswarm/e2e-harness/pull/49

After providing a more generic method to install chart resources, I realised that `InstallOperator` was nearly the same as the new `InstallResource` method.

Here is a refactoring of `InstallOperator` which is now just using `InstallResource`.

### CODE REVIEW

**Comment by MarcelMue** [comment]
Code checkout failed on Circle? Looks like outage or something 🤷‍♂️

**Review by xh3b4sd — COMMENTED** [review]
When we refactor this here it would be the better way to use our appr and helm client libs and stop using the shell out magic.

**Comment by TheoBrigitte** [comment]
CI is happy, are we happy?

**Review by fgimenez — APPROVED** [review]
LGTM, also agree with the refactor, but as part of other PR i guess.

**Review by indyfree — APPROVED** [review]
LGMT. Agree to refactor to use client libs in other PR

**Pull request merged**
