### PR TITLE
Longer wait for release status

### PR DESCRIPTION
**Pull request by indyfree**
Working on more e2e test installing charts e.g. https://github.com/giantswarm/chart-operator/pull/128, I noticed somtimes charts need more than 2 minutes to install. This pops up now, since we weren't using the `resource.WaitForStatus` from e2e-harness everywhere, and had longer MaxWait specified in the single e2e-tests.

### CODE REVIEW

**Review by xh3b4sd — APPROVED** [review]
Do we know why it takes longer sometimes? Something we can or have to do here?

**Comment by indyfree** [comment]
Unsure. I see Marcel encountered something similiar here #118 . I'll check operator logs.

**Review by rossf7 — APPROVED** [review]
LGTM when tested

**Comment by indyfree** [comment]
Vendored and run 3 consequitive runs with the previously flapping tests here https://github.com/giantswarm/chart-operator/pull/144. Error didn't show up again. Going ahead with this.

**Pull request merged**
