### PR TITLE
K8s 1.15

### PR DESCRIPTION
**Pull request by xh3b4sd**
Towards https://github.com/giantswarm/giantswarm/issues/6302.

### CODE REVIEW

**Review by sslavic — APPROVED** [review]
LGTM

**Review by MarcelMue — APPROVED** [review]
LGTM

**Review by TheoBrigitte — APPROVED** [review]

**Comment by sslavic** [comment]
@xh3b4sd if you don't mind, lets close this one in favor of https://github.com/giantswarm/e2e-harness/pull/209

**Comment by rossf7** [comment]
@sslavic This is from SWH IIRC and Tim has vacation. I think it can be closed to clean up.

**Pull request closed without merging**
