### PR TITLE
pkg/release: copy from pkg/framework/resource

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/giantswarm/issues/4355

### CODE REVIEW

**Comment by TheoBrigitte** [comment]
I am worried that this will break other packages since it is a breaking change.

Can we somehow get an idea of this impact ? I am thinking about something like godoc "imported by x packages". So we know what need to be updated along with this.

**Comment by kopiczko** [comment]
@TheoBrigitte please check https://github.com/giantswarm/giantswarm/issues/4355
I'm going to prepare vendor changes upfront w/ @MarcelMue

**Review by TheoBrigitte — APPROVED** [review]
All good then

**Comment by MarcelMue** [comment]
Can we instead of moving the package, just copy the package for now? We would like to move a bit faster here and get this done quickly without waiting for all vendor updates to go.

**Comment by kopiczko** [comment]
@MarcelMue done.

**Review by MarcelMue — APPROVED** [review]
Gogogo

**Comment by kopiczko** [comment]
I don't understand why CI doesn't run in this repo.

**Comment by kopiczko** [comment]
No build from yesterday https://circleci.com/gh/giantswarm/e2e-harness

**Comment by MarcelMue** [comment]
Uncertain, I have not seen this problem before.

**Comment by kopiczko** [comment]
screen shot 2018-10-10 at 11 13 16

**Comment by kopiczko** [comment]
I clicked start buildin and it builds master again. I merge that and let's see other PRs.

**Pull request merged**
